name: oauth-proxy
description: A Helm chart for oauth-proxy service
version: 0.0.3
home: https://k8s.community/
sources:
  - https://github.com/k8s-community/oauth-proxy
maintainers:
  - name: Elena Grahovac
    email: elena@grahovac.me
engine: gotpl
