apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  - port: {{ .Values.service.healthPort }}
    targetPort: {{ .Values.service.healthPort }}
    protocol: TCP
    name: {{ .Values.service.name }}-info
  selector:
    app: {{ template "fullname" . }}
  type: "{{ .Values.service.type }}"
